config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  scope controller: :landing do
  end

  scope controller: :flight do
    get "/search" => :search
  end

  scope "user", controller: :user do
    post "/login" => :login
    post "/signup" => :signup
    get "/logout" => :logout
    
    scope "booking", controller: :booking do
      get "/book/:flight_id" => :new, as: :booking_page
      post "/create" => :create, as: :new_booking
      get "/index" => :past_bookings, as: :your_bookings
      get "/manage" => :manage, as: :manage_booking
      patch "/update" => :update
      delete "/delete/:id" => :delete, as: :delete_booking
    end
  end
end

app/views/partials/_confirmation_modal.html.erb
<div class="ui modal confirmation-modal">
  <i class="close icon"></i>
  <div class="header">
    <i class="plane icon"></i> Confirm your booking data
  </div>
  <div class="description pad20">
    <div class="two column ui grid stackable">
      <div class="column">
        <%= render "partials/flight_description_table", { flight: flight } %>
      </div>
      <div class="column" id="passengers-information">
        <div class="ui header">Passengers Information</div>
        <div class="ui horizontal list" id="passengers-info-list">
        </div>
      </div>
    </div>
  </div>
  <div class="actions">
    <button type="button" class="ui button" onclick="closeModal();">Cancel</button>
    <button type="button" class="ui button submit-confirmation" onclick="activateSubmit();">OK</button>
  </div>
</div>

app/views/partials/_edit_booking_form.html.erb
<%= form_for booking, :url => update_path,
                        html: {
                                :onchange => "disableSubmit()",
                                :class => "ui form",
                                :name => "new-booking-form",
                                :id => "new-booking-form"
                              } do |f| %>
<% if session[:user_id].nil? %>
  <div class="field">
    <label for="send_email">Where to send the email: </label>
    <input type="email" name="send_email" value="<%= old_email params %>" required/>
  </div>
<% end %>
<div class="ui divider"></div>
<div class="inline field">
  <%= f.label :flight_id %>
  <%= f.select :flight_id, options_for_select(flights, flight.id), {}, id: "change_flight" %>
</div>
<p></p>
<div class="ui divider"></div>
<p></p>
<%= f.hidden_field :id %>
<%= f.hidden_field :booking_code %>
<%= f.hidden_field :price %>

<%= f.fields_for :passengers do |p| %>
<%= render "passenger_fields", f: p %>
<% end %>
<div class="field">
  <%= link_to_add_association f, :passengers, :class => "ui brown basic bottom right attached label" do %>
  <i class="user add icon"></i> Add Passenger
  <% end %>
</div>
<%= f.submit "Submit", :class => "ui basic m-button button disabled large submit-button" %>
<button type="button" class="ui button teal" onclick="confirmation()">Confirm Info</button>
<% end %>
<%= render "partials/confirmation_modal", { flight: flight } %>

app/views/partials/_error_message_display.html.erb
<% if flash[:errors] %>
<div class="ui grid error small message m-message four wide column flash">
  <i class="close icon"></i>
  <div class="content">
    <%= display_errors(flash[:errors]).html_safe %>
  </div>
</div>
<% end %>

app/views/partials/_flight_description_table.html.erb
<table class="ui celled stripped table" style="">
  <thead>
    <tr>
      <th>Description</th>
      <th>Details</th>
    </tr>
  </thead>
  <tbody>
    <%= flight_row "Departure Date", "calendar", format_date(flight.departure_date) %>
    <%= flight_row "Arrival Date", "calendar", format_date(flight.arrival_date) %>
    <%= flight_row "Departure Location", "marker", flight.departure_location %>
    <%= flight_row "Arrival Location", "location arrow", flight.arrival_location %>
    <%= flight_row "Airline", "plane", flight.airline.name %>
    <tr>
      <td><i class="money brown icon"></i> Price</td>
      <td>
        <button class="ui brown tag label">
        <i class="dollar icon"></i><span id="flight-price"><%= flight.price %></span>
        </button>
      </td>
    </tr>
  </tbody>
</table>

app/views/partials/_flight_form.html.erb
<%= form_tag search_path, :method => "get", :id => "search_flight_form", :class => "ui form" do |f| %>
<h1 class="ui dividing header" style="color: white">Search for Flight</h1>
<div class="ui inline cookie nag">
  <span class="title">
    Departure and Arrival can't be the same
  </span>
  <i class="close icon"></i>
</div>
<div class="field">
  <label style="color: white">Location</label>
  <div class="field">
    <select class="ui fluid dropdown" name="query[departure_location]" onchange="formCheck(this)">
      <option value="">Departure</option>
      <%= render partial: "partials/options_departures", collection: departures, as: :departures %>
    </select>
  </div>
  <div class="field">
    <select class="ui fluid dropdown" name="query[arrival_location]" onchange="formCheck(this)">
      <option value="">Arrival</option>
      <%= render partial: "partials/options_arrivals", collection: arrivals, as: :arrivals %>
    </select>
  </div>
</div>
<div class="field">
  <label style="color: white">Departure Date: </label>
  <div class="field">
    <input type="date" name="query[departure_date]">
  </div>
</div>
<div class="ui grid">
  <div class="ten wide column">
    <button class="ui basic button m-button" onclick="searchFlight(false)" type="button" id="search_flight">Search Flights</button>
  </div>
  <div class="six wide column">
    <div class="ui icon basic button m-button" id="help_icon" data-content="Submit empty form to get all flights" data-variation="inverted">
      <i class="help icon"></i>
    </div>
  </div>
</div>
<% end %>

app/views/partials/_flight_search_modal.html.erb
<div class="ui modal flight-search-modal">
  <i class="close icon"></i>
  <div class="header">
    Flights Search Result
  </div>
  <div class="content" id ="flights_results">
    <table class="ui celled table">
      <thead>
        <tr>
          <th colspan="2">
            <div class="ui labeled button" tabindex="0">
              <div class="ui basic button">
                <i class="search icon"></i> Total Result
              </div>
              <a class="ui basic left pointing label" id="result_count">
                
              </a>
            </div>
          </th>
          <th colspan="4">
            <div class="ui right floated pagination menu flight_result_pagination">
            </div>
          </th>
        </tr>
        <tr>
          <th>S/N</th>
          <th>Depature Location</th>
          <th>Arival Location</th>
          <th>Departure Date</th>
          <th>Price</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      </tbody>
      <tfoot>
      <tr>
        <th colspan="6">
          <div class="ui right floated pagination menu flight_result_pagination">
          </div>
        </th>
      </tr>
      </tfoot>
    </table>
    <!-- <div id="pagination"></div> -->
  </div>
</div>

app/views/partials/_footer.html.erb
<div class="ui centered grid" id="footer-container">
  <div class="ui middle aligned grid container">
    <div class="ui sixteen wide column">
    <div class="ui three column grid stackable">
      <div class="column left">
        <div class="bottom-footer-side footer-text-color">&copy; 2016, Moscavion</div>
      </div>
      <div class="column">
        <div class="footer-text-color logo_font">
          Enjoy your flight
        </div>
      </div>
      <div class="column">
        <div class="bottom-footer-side footer-text-color">
          Follow us:
          <a href="#" class="my-link"><i class="facebook icon"></i></a>
          <a href="#" class="my-link"><i class="twitter icon"></i></a>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/partials/_header.html.erb
<div class="ui centered grid" id="header-container">
  <div class="ui middle aligned grid container">
    <div class="ui sixteen wide column">
      <div class="ui three column grid stackable">
        <div class="column">
          <div class="ui two column grid stackable">
            <div class="column centered">
              <a href="<%= your_bookings_path %>" role="button" class="my-link <%= disable_profile_link %>"><i class="home icon"></i>Profile</a>
            </div>
            <div class="column centered">
              <div><a href="#" onclick="searchFlight(true)" role="button" class="my-link ui button basic"><i class="plane icon"></i> All flight</a></div>
            </div>
          </div>
        </div>
        <div class="column">
          <div class="middle aligned">
            <span id="logo"><a href="/"><h1 class="ui first header">Moscavion</h1></a></span>
          </div>
        </div>
        <div class="column">
          <div class="ui two column grid stackable">
            <div class="column centered">
              <div class="">
                <a href="#" onclick="showManageForm()" role="button" class="my-link ui button basic"><i class="edit icon"></i> Manage</a>
              </div>
            </div>
            <div class="column centered">
              <div class="">
                <% if session[:user_id].nil? %>
                <span class="ui button basic">
                  <a href="#" role="button" class="my-link" onclick="openSignin()">Sign In</a> |
                  <a href="#" role="button" class="my-link" onclick="openSignup()">Sign Up</a>
                </span>
                <% else %>
                <a href="<%= logout_path %>" role="button" class="my-link ui button basic" remote="true"><i class="sign out icon"></i>Log Out</a>
                <% end %>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_login_msg.html.erb
<% if session[:user_id].nil? %>
<div class="ui grid info mini message m-message flash_login">
	<i class="close icon"></i>
	<div class="content">
		<div class="twelve wide column">
			<i class="info circle icon"></i>
			For access to your past booking reservations, please <a onclick="openSignin()" role="button">Sign In</a> /
			<a role="button" onclick="openSignup()">Sign Up</a>
		</div>
	</div>
</div>
<% end %>

app/views/partials/_notice_message.html.erb
<% if flash[:notice] %>
<div class="ui grid positive small message m-message four wide column flash">
	<i class="close icon"></i>
	<div class="content">
		<i class="info icon"></i>
		<%= flash[:notice] %>
	</div>
</div>
<% end %>

app/views/partials/_options_arrivals.html.erb
<option value="<%= arrivals.arrival_location %>">
<%= arrivals.arrival_location %>
</option>

app/views/partials/_options_departures.html.erb
<option value="<%= departures.departure_location %>">
<%= departures.departure_location %>
</option>

app/views/partials/_preloader.html.erb
<div id="loading">
  <div id="loading-center">
    <div id="loading-center-absolute">
      <div class="row">
        <div class="column eight wide centered">
          <div class="ui three column grid">
            <div class="column twelve wide centered">
              <h1 class="ui icon header">
              <div class="ui active large inline loader"></div>
              <div class="content brown">
                Moscavion
                <p class="sub header brown">book your flight</p>
              </div>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_search_booking_form.html.erb
<div class="ui modal small manage-form">
  <div class="header">
    Search with your booking code to edit
  </div>
  <div class="content">
    <%= form_tag manage_booking_url, :method => 'get', :class => "ui form" do %>
    <div class="field">
      <label>Booking Code</label>
      <input type="text" name="booking[booking_code]" >
    </div>
    <button class="ui button">Find</button>
    <% end %>
  </div>
  <div class="actions">
    
  </div>
</div>