config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  scope controller: :landing do
  end

  scope controller: :flight do
    get "/search" => :search
  end

  scope "user", controller: :user do
    post "/login" => :login
    post "/signup" => :signup
    get "/logout" => :logout
    
    scope "booking", controller: :booking do
      get "/book/:flight_id" => :new, as: :booking_page
      post "/create" => :create, as: :new_booking
      get "/index" => :past_bookings, as: :your_bookings
      get "/manage" => :manage, as: :manage_booking
      patch "/update" => :update
      delete "/delete/:id" => :delete, as: :delete_booking
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookings
  has_secure_password

  validates :first_name,
            :last_name,
            presence: true,
            allow_nil: false

  validates :email,
            presence: true,
            format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
            allow_nil: false,
            uniqueness: true

  validates :password,
            presence: true,
            confirmation: true,
            allow_nil: false,
            length: { minimum: 6 }
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :user_blank?, only: [:login]

  def login
    MoscavionUser.new(request, login_params, :login)
    redirect_to root_path
  end

  def signup
    MoscavionUser.new(request, user_params, :signup)
    redirect_to root_path
  end

  def logout
    session.clear
    flash[:notice] = "You have successfully logged out"
    redirect_to root_path
  end

  private

  def login_params
    params.require(:user_details).permit(:email, :password)
  end

  def user_params
    params.require(:user).permit(
                                 :first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation
                                )
  end

  def user_blank?
    if prune_params.blank? || prune_params.size < 2
      flash[:errors] = "User details cannot be empty"
      redirect_to :back
      return
    end
  end

  def prune_params
    login_params.delete_if { |_key, value| value.blank? }
  end
end

app/helpers/user_helper.rb
module UserHelper
  def new_user
    User.new
  end
end

app/views/user/_login_page.html.erb
<div class="ui small modal signin-modal">
  <i class="close icon"></i>
  <div class="header">
    <h2>Login</h2>
  </div>
  <div class="content">
    <%= form_tag login_url, :class=>"ui form" do |f| %>
    <div class="field">
      <label>Email</label>
      <input type="email" name="user_details[email]">
    </div>
    <div class="field">
      <label>Password</label>
      <input type="password" name="user_details[password]">
    </div>
      <button type="submit" name="submit" class="ui button basic m-button">Login</button>
    <% end %>
  </div>
</div>

app/views/user/_signup.html.erb
<div class="ui modal signup-modal small">
  <i class="close icon"></i>
  <div class="header">
    Signup
  </div>
  <div class="content">
    <%= form_for new_user, url: signup_url , html: { class: "ui form", id: "signup-form" } do |f| %>
      <div class="field">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, { required: true } %>
      </div>
      <div class="field">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, { required: true } %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email, { required: true } %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, { required: true, minlength: 6 } %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, { required: true, minlength: 6, oninput: "confirmPassword()" } %>
      </div>
      <button class="ui basic m-button button disabled" id="signup-submit">Submit</button>
    <% end %>
  </div>
</div>